### PR TITLE
COM-172 Update Program labels

### PR DESCRIPTION
**Pull request by prashantsable1991**
Updated Program labels.

### CODE REVIEW

**Comment by tmvumbi2** [comment]
@prashantsable1991 There is a validation pattern on the ART number field that prevents capturing free text

image

**[UPDATE]**
The fix actually needs to be done on the DB

**Comment by tmvumbi2** [comment]
@prashantsable1991 The ID field was previously mandatory, it is now optional (which is not on the story's requirement)

**Review by tmvumbi2 — DISMISSED** [review]
Thanks @prashantsable1991 , the PR is looking great. I left a comment about a small fix on the ID field

**Comment by prashantsable1991** [comment]
@tmvumbi2 I pushed the fixes on metadata repo please have a look on that. Thanks!

**Pull request merged**
