### PR TITLE
COMRS-47 Translate relationships in registration form

### PR DESCRIPTION
**Pull request by lauravignoli**
https://jembiprojects.jira.com/browse/COMRS-47

### CODE REVIEW

**Comment by prashantsable1991** [comment]
> https://jembiprojects.jira.com/browse/COMRS-47

I have tested relationship types all are working fine expect in some pages translations are not working in ui. You have did nice work!!!
relationshiptypes-config

**Comment by prashantsable1991** [comment]
> https://jembiprojects.jira.com/browse/COMRS-47

**Comment by lauravignoli** [comment]
@prashantsable1991 I added the translations to that page:

translaterel

**Comment by prashantsable1991** [comment]
> @prashantsable1991 I added the translations to that page:
> 
> translaterel

@lauravignoli thanks for the changes it's working fine. 
For there is small change required in adt module please refer below image:
comrs-47 4

**Pull request merged**
