### PR TITLE
COMRS-141 Make additional id types translatable and show ART and CNI in search result

### PR DESCRIPTION
**Pull request by lauravignoli**
https://jembiprojects.jira.com/browse/COMRS-141

### CODE REVIEW

**Review by rubailly — APPROVED** [review]
LGTM

**Review by rubailly — COMMENTED** [review]
Additional Identifiers translates to "Identifiants supplémentaires"

**Review by rubailly — CHANGES_REQUESTED** [review]
Can you also add "| translate" to both editPatient.html and newPatient.html? -Currently, translation is not working for the primary identifier when editing or creating a patient.

**Comment by lauravignoli** [comment]
> Can you also add "| translate" to both editPatient.html and newPatient.html? -Currently, translation is not working for the primary identifier when editing or creating a patient.

**Comment by lauravignoli** [comment]
@rubailly What translations missing are you talking about? This? 
patientid

**Pull request merged**
